## Problem Description

In the scope of the DARGMINTS project, an annotation project was carried out which consisted of annotating argumentation structures in opinion articles published in the Público newspaper. The annotation included several layers:

1. Selecting text spans that are taken to have an argumentative role (either as premises or conclusions of arguments) -- these are Argumentative Discourse Units (ADU).
2. Connecting such ADUs through support or attack relations.
3. Classifying the propositional content of ADUs as propositions of fact, propositions of value, or propositions of policy; within propositions of value, distinguish between those with a positive (+) or negative (-) connotation.

In a proposition of fact, the content corresponds to a piece of information that can be checked for truthness. This does not usually happen with propositions of value, which denote value judgments with a strong subjective nature; often, they also have a (positive or negative) polarity attached. A proposition of policy prescribes or suggests a certain line of action, often mentioning the agents or entities that are capable of carrying out such policies.

The aim of this assignment is to build a classifier of types of ADUs, thus focusing on the last annotation step described above. For that, you have access to two different files:

- A file containing the content of each annotated ADU span and its 5-class classification: Value, Value(+), Value(-), Fact, or Policy. For each ADU, we also know the annotator and the document from which it has been taken.
- A file containing details for each opinion article that has been annotated, including the full article content.
Besides ADU contents, you can make use of any contextual information provided in the corresponding opinion article.

Each opinion article has been annotated by 3 different annotators. For that reason, you will find in the ADU file an indication of which annotator has obtained the ADU. It may happen that the same ADU has been annotated by more than one annotator. When that is the case, they do not necessarily agree on the type of proposition.

How good a classifier (or set of classifiers) can you get? Don't forget to properly split the dataset in a sensible manner, so that you have a proper test set. Start by obtaining an arbitrary baseline, against which you can then compare your improvements.

Portuguese NLKT: https://www.nltk.org/howto/portuguese_en.html

### Data Analysis

In [31]:
import pandas as pd
data = pd.read_excel('OpArticles/OpArticles.xlsx')
data_ADU = pd.read_excel('OpArticles/OpArticles_ADUs.xlsx')

In [32]:
# TODO

display("Articles Data", data.head())
display("ADU Data", data_ADU.head())

'Articles Data'

article_id  \
0  5d04a31b896a7fea069ef06f   
1  5d04a3fc896a7fea069f0717   
2  5d04a455896a7fea069f07ab   
3  5d04a52f896a7fea069f0921   
4  5d04a8d7896a7fea069f6997   

                                               title  \
0            Pouco pão e muito circo, morte e bocejo   
1    Portugal nos Mundiais de Futebol de 2010 e 2014   
2                          Futebol, guerra, religião   
3  As razões do Qatar para acolher o Mundial em 2022   
4                     A política no campo de futebol   

                                    authors  \
0                  ['José Vítor Malheiros']   
1                       ['Rui J. Baptista']   
2                         ['Fernando Belo']   
3  ['Hamad bin Khalifa bin Ahmad Al Thani']   
4                        ['Carlos Nolasco']   

                                                body  \
0  O poeta espanhol António Machado escrevia, uns...   
1  “O mais excelente quadro posto a uma luz logo ...   
2  1. As sociedades humanas parecem ser regidas p...   
3  Este foi um Mundial incrível. Vimos actuações ...   
4  O futebol sempre foi um jogo aparentemente sim...   

                                    meta_description  topics  \
0  É tudo cómico na FIFA, porque todos os dias a ...  Sports   
1  Deve ser evidenciado o clima favorável criado ...  Sports   
2  O futebol parece ser um sucedâneo quer da lei ...  Sports   
3  Queremos cooperar plenamente com a investigaçã...  Sports   
4  Retirar a expressão política do futebol é reti...  Sports   

                                            keywords         publish_date  \
0  ['Brasil', 'Campeonato do Mundo', 'Desporto', ...  2014-06-17 00:16:00   
1  ['Brasil', 'Campeonato do Mundo', 'Coreia do N...  2014-07-05 02:46:00   
2  ['A guerra na Síria', 'Desporto', 'Futebol', '...  2014-07-12 16:05:33   
3  ['Desporto', 'FIFA', 'Futebol', 'Mundial de fu...  2014-07-27 02:00:00   
4  ['Albânia', 'Campeonato da Europa', 'Desporto'...  2014-10-23 00:16:00   

                                       url_canonical  
0  https://www.publico.pt/2014/06/17/desporto/opi...  
1  https://www.publico.pt/2014/07/05/desporto/opi...  
2  https://www.publico.pt/2014/07/12/desporto/opi...  
3  https://www.publico.pt/2014/07/27/desporto/opi...  
4  https://www.publico.pt/2014/10/23/desporto/opi...

'ADU Data'

article_id annotator  node          ranges  \
0  5d04a31b896a7fea069ef06f         A     0  [[2516, 2556]]   
1  5d04a31b896a7fea069ef06f         A     1  [[2568, 2806]]   
2  5d04a31b896a7fea069ef06f         A     3  [[3169, 3190]]   
3  5d04a31b896a7fea069ef06f         A     4  [[3198, 3285]]   
4  5d04a31b896a7fea069ef06f         A     6  [[4257, 4296]]   

                                              tokens  label  
0           O facto não é apenas fruto da ignorância  Value  
1  havia no seu humor mais jornalismo (mais inves...  Value  
2                              É tudo cómico na FIFA  Value  
3  o que todos nós permitimos que esta organizaçã...  Value  
4            não nos fazem rir à custa dos poderosos  Value

In [33]:
print("---------------------Articles---------------------")
data.info()
print("---------------------ADU---------------------")
data_ADU.info()

---------------------Articles---------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   article_id        373 non-null    object
 1   title             373 non-null    object
 2   authors           373 non-null    object
 3   body              373 non-null    object
 4   meta_description  373 non-null    object
 5   topics            373 non-null    object
 6   keywords          373 non-null    object
 7   publish_date      373 non-null    object
 8   url_canonical     373 non-null    object
dtypes: object(9)
memory usage: 26.4+ KB
---------------------ADU---------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16743 entries, 0 to 16742
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   article_id  16743 non-null  object
 1   annotator   16743 n

#### Description of tables

In [34]:
display("Articles data", data.describe(include='all'))
display("ADU data", data_ADU.describe(include='all'))

'Articles data'

article_id  \
count                        373   
unique                       373   
top     5cf46cea896a7fea06003dd2   
freq                           1   

                                                    title  \
count                                                 373   
unique                                                373   
top     Como parar a charlatanice que são as medicinas...   
freq                                                    1   

                                      authors  \
count                                     373   
unique                                    373   
top     ['Jean-Michel Casa', 'Christof Weil']   
freq                                        1   

                                                     body  \
count                                                 373   
unique                                                373   
top     Atualmente, o excesso de peso é o principal re...   
freq                                                    1   

                                         meta_description  topics  \
count                                                 373     373   
unique                                                373       8   
top     Temos de “atacar” a máquina fiscal espanhola. ...  Sports   
freq                                                    1      52   

                       keywords         publish_date  \
count                       373                  373   
unique                      356                  372   
top     ['Desporto', 'Opinião']  2016-08-04 00:30:00   
freq                          4                    2   

                                            url_canonical  
count                                                 373  
unique                                                373  
top     https://www.publico.pt/2016/02/09/desporto/opi...  
freq                                                    1

'ADU data'

article_id annotator          node      ranges  \
count                      16743     16743  16743.000000       16743   
unique                       373         4           NaN       11929   
top     5cf464b6896a7fea06ffbb9d         B           NaN  [[0, 138]]   
freq                         142      5226           NaN           6   
mean                         NaN       NaN     14.938960         NaN   
std                          NaN       NaN     14.033932         NaN   
min                          NaN       NaN      0.000000         NaN   
25%                          NaN       NaN      4.000000         NaN   
50%                          NaN       NaN     11.000000         NaN   
75%                          NaN       NaN     21.000000         NaN   
max                          NaN       NaN    100.000000         NaN   

               tokens  label  
count           16743  16743  
unique          12008      5  
top     Não é verdade  Value  
freq                8   8102  
mean              NaN    NaN  
std               NaN    NaN  
min               NaN    NaN  
25%               NaN    NaN  
50%               NaN    NaN  
75%               NaN    NaN  
max               NaN    NaN

### Preprocessing

#### Tokenization

In [35]:
def column2string(column):
    str_result = ""
    for i in column:
        str_result += i + ""
    return str_result

In [37]:
# Portuguese nltk
import nltk.test.portuguese_en_fixt 
import nltk
import re

portuguese_tokenizer=nltk.data.load('tokenizers/punkt/portuguese.pickle')  

#### Stemming

In [71]:
import nltk.stem

corpus = []
counter = 0
ps = nltk.stem.RSLPStemmer()
for i in range(0, data_ADU['tokens'].size):
    token = data_ADU['tokens'][i]
    # to lower-case
    token = token.lower()
    # split into tokens, apply stemming and remove stop words
    token = ' '.join([ps.stem(w) for w in token.split()])
    corpus.append(token)
    counter += 1


o fact não é apen frut da ignor
hav no seu hum mais jorn (mal investigação, mais preocup em aprofund e contextual a história, mais isenç no relato, mais preocup social, mais urg de denunciar) do que em muit peç real jorn
é tud cómic na fif
o que tod nó permit que est organiz faç é total absurd e sem sent
não no faz rir à cust do poder


In [69]:
print(data_ADU['tokens'].size)
print(counter)


16743
16743


#### Lemmatization

In [40]:
# TODO

#lemmatizer = LemmatizerModel.pretrained("lemma", "pt") \
#        .setInputCols(["token"]) \
#        .setOutputCol("lemma")
#nlp_pipeline = Pipeline(stages=[document_assembler, tokenizer, lemmatizer])
#light_pipeline = LightPipeline(nlp_pipeline.fit(spark.createDataFrame([['']]).toDF("text")))
#results = light_pipeline.fullAnnotate(text_tokens)

### N-Gram Language Models

In [41]:
# TODO - António

### Text Classification

In [130]:
# TODO

from sklearn.feature_extraction.text import CountVectorizer


vectorizer = CountVectorizer()
#X = vectorizer.fit_transform(corpus).toarray()
X = vectorizer.fit_transform(corpus).toarray()



print(X.shape)

y = data_ADU['label']

print(X.shape, y.shape)


(6, 6)
(6, 6) (16743,)


In [132]:
# TODO - improve division

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

print("\nLabel distribution in the training set:")
print(y_train.value_counts())

print("\nLabel distribution in the test set:")
print(y_test.value_counts())

ValueError: Found input variables with inconsistent numbers of samples: [6, 16743]

#### Models

In [89]:
# TODO - Model evaluation

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

def model_evaluation(y_pred, y_test):
  print("------------------Confusion Matrix------------------")
  print(confusion_matrix(y_test, y_pred))
  print("------------------Accuracy------------------")
  print(accuracy_score(y_test, y_pred))
  print("------------------Precision------------------")
  print(precision_score(y_test, y_pred, average=None))
  print("------------------Recall------------------")
  print(recall_score(y_test, y_pred, average=None))
  print("------------------F1------------------")
  print(f1_score(y_test, y_pred, average=None))



In [115]:
def display(results):
    print(f'Best parameters are: {results.best_params_}')
    print("\n")
    mean_score = results.cv_results_['mean_test_score']
    std_score = results.cv_results_['std_test_score']
    params = results.cv_results_['params']
    for mean,std,params in zip(mean_score,std_score,params):
        print(f'{round(mean,3)} + or -{round(std,3)} for the {params}')

In [ ]:
from sklearn.model_selection import cross_val_score

def cross_validation(model, kfold, X, y):
  return cross_val_score(model, X, y, cv=kfold)

In [124]:
# TODO - Naive Bayes

from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV

clfNB = MultinomialNB()
#parameters= {
  #"alpha":[0, 0.5, 1.0, 1.5, 2.0],
  #"fit_prior":[True, False],
#}

#cv = GridSearchCV(clfNB,parameters,cv=5)
#cv.fit(X_train, y_train.ravel())

#display(cv)

clfNB.fit(X_train, y_train)
y_pred = clfNB.predict(X_test)
print(y_pred)

model_evaluation(y_pred, y_test)


['Value' 'Value' 'Value(-)' ... 'Value' 'Value' 'Fact']
------------------Confusion Matrix------------------
[[ 246    1  398   14   37]
 [   9    7  122    0    0]
 [ 190    4 1368   22   96]
 [  32    0  201   31   10]
 [  55    1  354    2  149]]
------------------Accuracy------------------
0.5377724693938489
------------------Precision------------------
[0.46240602 0.53846154 0.55996725 0.44927536 0.51027397]
------------------Recall------------------
[0.35344828 0.05072464 0.81428571 0.11313869 0.26559715]
------------------F1------------------
[0.40065147 0.09271523 0.66359447 0.18075802 0.34935522]


In [95]:
from sklearn.naive_bayes import GaussianNB

clfGNB = GaussianNB()
clfGNB.fit(X_train, y_train)

y_pred = clfGNB.predict(X_test)
print(y_pred)

model_evaluation(y_pred, y_test)

['Value(+)' 'Policy' 'Value(+)' ... 'Fact' 'Fact' 'Value']
------------------Confusion Matrix------------------
[[229  71 131 109 156]
 [  4  78  28  13  15]
 [305 251 452 283 389]
 [ 36  49  45 120  24]
 [ 57  41 109  67 287]]
------------------Accuracy------------------
0.34816363093460734
------------------Precision------------------
[0.36291601 0.15918367 0.59084967 0.2027027  0.32950631]
------------------Recall------------------
[0.32902299 0.56521739 0.26904762 0.4379562  0.51158645]
------------------F1------------------
[0.34513941 0.24840764 0.36973415 0.27713626 0.40083799]


In [127]:
# TODO - Logistic Regression
# Regularization is applied by default

from sklearn.linear_model import LogisticRegression
import numpy as np

clfLR = LogisticRegression(penalty='l2', C=0.615848211066026, solver='liblinear')
#parameters = {
  #"penalty": ["l1", "l2"],
  #"C": np.logspace(-4, 4, 20),
  #"solver": ["liblinear"]
#}

#cv = GridSearchCV(clfLR,parameters,cv=5)
#cv.fit(X_train, y_train.ravel())

#display(cv)


clfLR.fit(X_train, y_train)

y_pred = clfLR.predict(X_test)
print(y_pred)

model_evaluation(y_pred, y_test)


['Fact' 'Value' 'Value' ... 'Value' 'Value' 'Fact']
------------------Confusion Matrix------------------
[[ 240    1  400   11   44]
 [   9   30   93    1    5]
 [ 202   22 1297   43  116]
 [  28    4  173   58   11]
 [  54    6  333    2  166]]
------------------Accuracy------------------
0.5347865034338608
------------------Precision------------------
[0.45028143 0.47619048 0.56489547 0.50434783 0.48538012]
------------------Recall------------------
[0.34482759 0.2173913  0.77202381 0.21167883 0.29590018]
------------------F1------------------
[0.39056143 0.29850746 0.65241449 0.29820051 0.36766334]


In [119]:
# TODO - Decision Tree

from sklearn.tree import DecisionTreeClassifier

clfDT = DecisionTreeClassifier(max_depth=5)
#parameters= {
  #"criterion":['gini', 'entropy'],
  #"splitter":['best', 'random'],
  #"max_depth": [2,3,4,5, None]
#}

#cv = GridSearchCV(clfDT,parameters,cv=5)
#cv.fit(X_train, y_train.ravel())

#display(cv)

clfDT.fit(X_train, y_train)

y_pred = clfDT.predict(X_test)
print(y_pred)

model_evaluation(y_pred, y_test)

['Value' 'Value' 'Value' ... 'Value' 'Value' 'Fact']
------------------Confusion Matrix------------------
[[  24    0  670    0    2]
 [   0   13  125    0    0]
 [  13   14 1649    0    4]
 [   1    0  271    1    1]
 [  10    2  547    1    1]]
------------------Accuracy------------------
0.5040310540459839
------------------Precision------------------
[0.5        0.44827586 0.50551809 0.5        0.125     ]
------------------Recall------------------
[0.03448276 0.0942029  0.98154762 0.00364964 0.00178253]
------------------F1------------------
[0.06451613 0.15568862 0.66734116 0.00724638 0.00351494]


In [131]:
# TODO - Random Forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

clfRF = RandomForestClassifier(max_depth=50)
#parameters= {
   #"n_estimators":[5,10,50,100,250],
   #"max_depth":[2,4,8,16,32,None]
#}

#cv = GridSearchCV(clfRF,parameters,cv=5)
#cv.fit(X_train, y_train.ravel())

#display(cv)

clfRF.fit(X_train, y_train)

y_pred = clfRF.predict(X_test)
print(y_pred)

model_evaluation(y_pred, y_test)

['Value' 'Value' 'Value' ... 'Value' 'Value' 'Fact']
------------------Confusion Matrix------------------
[[  68    0  625    1    2]
 [   0    5  133    0    0]
 [  24    4 1646    0    6]
 [   2    0  270    2    0]
 [   5    0  546    0   10]]
------------------Accuracy------------------
0.5168707076739325
------------------Precision------------------
[0.68686869 0.55555556 0.51118012 0.66666667 0.55555556]
------------------Recall------------------
[0.09770115 0.03623188 0.9797619  0.00729927 0.01782531]
------------------F1------------------
[0.17106918 0.06802721 0.67183673 0.01444043 0.03454231]


In [116]:
display(cv)

Best parameters are: {'max_depth': None, 'n_estimators': 250}


0.479 + or -0.0 for the {'max_depth': 2, 'n_estimators': 5}
0.479 + or -0.0 for the {'max_depth': 2, 'n_estimators': 10}
0.479 + or -0.0 for the {'max_depth': 2, 'n_estimators': 50}
0.479 + or -0.0 for the {'max_depth': 2, 'n_estimators': 100}
0.479 + or -0.0 for the {'max_depth': 2, 'n_estimators': 250}
0.48 + or -0.0 for the {'max_depth': 4, 'n_estimators': 5}
0.479 + or -0.0 for the {'max_depth': 4, 'n_estimators': 10}
0.479 + or -0.0 for the {'max_depth': 4, 'n_estimators': 50}
0.479 + or -0.0 for the {'max_depth': 4, 'n_estimators': 100}
0.479 + or -0.0 for the {'max_depth': 4, 'n_estimators': 250}
0.48 + or -0.0 for the {'max_depth': 8, 'n_estimators': 5}
0.48 + or -0.001 for the {'max_depth': 8, 'n_estimators': 10}
0.479 + or -0.0 for the {'max_depth': 8, 'n_estimators': 50}
0.48 + or -0.0 for the {'max_depth': 8, 'n_estimators': 100}
0.479 + or -0.0 for the {'max_depth': 8, 'n_estimators': 250}
0.482 + or -0.003 fo

In [112]:
# TODO - SVM 

from sklearn import svm

clfSVC = svm.SVC(kernel="sigmoid")

clfSVC.fit(X_train, y_train)

y_pred = clfSVC.predict(X_test)
print(y_pred)

model_evaluation(y_pred, y_test)

['Fact' 'Fact' 'Value' ... 'Value' 'Value(-)' 'Fact']
------------------Confusion Matrix------------------
[[ 267    2  351    2   74]
 [  30    8   86    0   14]
 [ 445   10 1010    2  213]
 [  80    0  157    7   30]
 [ 179    2  278    0  102]]
------------------Accuracy------------------
0.41624365482233505
------------------Precision------------------
[0.26673327 0.36363636 0.53666312 0.63636364 0.23556582]
------------------Recall------------------
[0.38362069 0.05797101 0.60119048 0.02554745 0.18181818]
------------------F1------------------
[0.31467295 0.1        0.56709714 0.04912281 0.20523139]


### Regularization

In [ ]:
# TODO - Leonor

